export const REGIONS = [
  { code: "WAFR", fullName: "West Africa", category: "Region" },
  { code: "SAFR", fullName: "South Africa", category: "Region" },
  { code: "EAFR", fullName: "East Africa", category: "Region" },
  { code: "ECI", fullName: "East Coast India", category: "Region" },
  { code: "WCI", fullName: "West Coast India", category: "Region" },
  { code: "SEASIA", fullName: "South East Asia", category: "Region" },
  { code: "SEA", fullName: "South East Asia", category: "Region" },
  { code: "AG", fullName: "Arabian Gulf", category: "Region" },
  { code: "PG", fullName: "Persian Gulf", category: "Region" },
  { code: "MED", fullName: "Mediterranean", category: "Region" },
  { code: "BSEA", fullName: "Black Sea", category: "Region" },
  { code: "BALTIC", fullName: "Baltic Sea", category: "Region" },
  { code: "USEC", fullName: "US East Coast", category: "Region" },
  { code: "USGC", fullName: "US Gulf Coast", category: "Region" },
  { code: "USWC", fullName: "US West Coast", category: "Region" },
  { code: "WCCA", fullName: "West Coast Central America", category: "Region" },
  { code: "ECSA", fullName: "East Coast South America", category: "Region" },
  { code: "GOA", fullName: "Gulf of Aden", category: "Region" },
  { code: "HRA", fullName: "High Risk Area", category: "Region" },
  { code: "COGH", fullName: "Cape of Good Hope", category: "Region" },
  { code: "WW", fullName: "World Wide", category: "Region" },
  { code: "ARAG", fullName: "Arabian Gulf", category: "Region" },
  { code: "UPRIVER", fullName: "Upriver Argentina", category: "Region" },
  { code: "S.CHINA", fullName: "South China", category: "Region" },
];

export const PORTS = [
  { code: "BIK", fullName: "Bandar Imam Khomeini, Iran", category: "Port" },
  { code: "KANDLA", fullName: "Kandla, India", category: "Port" },
  { code: "KAKINADA", fullName: "Kakinada, India", category: "Port" },
  { code: "VIZAG", fullName: "Visakhapatnam, India", category: "Port" },
  { code: "MUMBAI", fullName: "Mumbai, India", category: "Port" },
  { code: "HAZIRA", fullName: "Hazira, India", category: "Port" },
  { code: "LUMUT", fullName: "Lumut, Malaysia", category: "Port" },
  { code: "SURABAYA", fullName: "Surabaya, Indonesia", category: "Port" },
  { code: "BAHODOPI", fullName: "Bahodopi, Indonesia", category: "Port" },
  { code: "SANTOS", fullName: "Santos, Brazil", category: "Port" },
  { code: "PARANAGUA", fullName: "Paranaguá, Brazil", category: "Port" },
  { code: "AQABA", fullName: "Aqaba, Jordan", category: "Port" },
  { code: "PIVDENNIY", fullName: "Pivdenniy, Ukraine", category: "Port" },
  { code: "ISKENDERUN", fullName: "Iskenderun, Turkey", category: "Port" },
  { code: "DURBAN", fullName: "Durban, South Africa", category: "Port" },
  { code: "BUSHEHR", fullName: "Bushehr, Iran", category: "Port" },
  { code: "DOHA", fullName: "Doha, Qatar", category: "Port" },
  { code: "HODEIDAH", fullName: "Hodeidah, Yemen", category: "Port" },
  { code: "BUKPYUNG", fullName: "Bukpyung, South Korea", category: "Port" },
  { code: "GUANGZHOU", fullName: "Guangzhou, China", category: "Port" },
  { code: "TAIPEI", fullName: "Taipei, Taiwan", category: "Port" },
  { code: "PORBANDAR", fullName: "Porbandar, India", category: "Port" },
  { code: "LANSHAN", fullName: "Lanshan, China", category: "Port" },
  { code: "UMM QASAR", fullName: "Umm Qasar, Iraq", category: "Port" },
  { code: "PORT KELANG", fullName: "Port Klang, Malaysia", category: "Port" },
];

export const VESSEL_SIZES = [
  { name: "Handymax", minDwt: 10000, maxDwt: 49999, description: "HMAX — versatile geared vessels" },
  { name: "Supramax", minDwt: 50000, maxDwt: 59999, description: "SMX / SMAX — common bulk carrier" },
  { name: "Ultramax", minDwt: 60000, maxDwt: 69999, description: "UMX / UMAX — modern design" },
  { name: "Panamax", minDwt: 70000, maxDwt: 79999, description: "Fits original Panama Canal locks" },
  { name: "Kamsarmax", minDwt: 80000, maxDwt: 89999, description: "Max size for Kamsar port, Guinea" },
  { name: "Baby Cape", minDwt: 90000, maxDwt: 199999, description: "Post-Panamax transitional size" },
  { name: "Capesize", minDwt: 200000, maxDwt: null, description: "Too large for Panama/Suez, must round capes" },
];
